User.create(first_name: "James", last_name: "Bomotti", is_teacher: true, email: "lds1233@gmail.com")
User.create(first_name: "Lisa", last_name: "Swanson", is_teacher: true, email: "lds1233@gmail.com")
User.create(first_name: "Erin", last_name: "Beitel", is_teacher: true, email: "lds1233@gmail.com")
User.create(first_name: "Devin", last_name: "Lie", is_teacher: true, email: "lds1233@gmail.com")
User.create(first_name: "Marco", last_name: "Arities", is_teacher: true, email: "lds1233@gmail.com")
User.create(first_name: "Jordan", last_name: "Stenvers", is_teacher: true, email: "lds1233@gmail.com")
User.create(first_name: "Ken", last_name: "Pimento", is_teacher: true, email: "lds1233@gmail.com")
User.create(first_name: "Mark", last_name: "Saches", is_teacher: true, email: "lds1233@gmail.com")
School.create(name: "Novato High School", city: "Novato", state: "CA", district: "Unified")
School.create(name: "San Rafael High School", city: "San Rafael", state: "CA", district: "Unified")
School.create(name: "Tamalpais High School", city: "Mill Valley", state: "CA", district: "Unified")
School.create(name: "Redwood High School", city: "Larkspur", state: "CA", district: "Unified")
List.create(quantity: 2, item: "white boards")
List.create(quantity: 20, item: "dry erasers")
List.create(quantity: 3, item: "tissue")
List.create(quantity: 1, item: "projector")
List.create(quantity: 10, item: "reams of white copy paper")
List.create(quantity: 10, item: "cleaning supplies")
List.create(quantity: 10, item: "hand santitizer")
List.create(quantity: 250, item: "iPads")
SchoolUserList.create(school_id: 1, user_id: 1, list_id: 1)
SchoolUserList.create(school_id: 1, user_id: 2, list_id: 2)
SchoolUserList.create(school_id: 1, user_id: 3, list_id: 3)
SchoolUserList.create(school_id: 1, user_id: 4, list_id: 4)
SchoolUserList.create(school_id: 1, user_id: 5, list_id: 5)
SchoolUserList.create(school_id: 1, user_id: 6, list_id: 6)
SchoolUserList.create(school_id: 1, user_id: 7, list_id: 7)
SchoolUserList.create(school_id: 1, user_id: 8, list_id: 8)
SchoolUserList.create(school_id: 1, user_id: 1, list_id: 2)
SchoolUserList.create(school_id: 1, user_id: 2, list_id: 3)
SchoolUserList.create(school_id: 1, user_id: 3, list_id: 4)
SchoolUserList.create(school_id: 1, user_id: 4, list_id: 5)
SchoolUserList.create(school_id: 1, user_id: 5, list_id: 6)
SchoolUserList.create(school_id: 1, user_id: 6, list_id: 7)
SchoolUserList.create(school_id: 1, user_id: 7, list_id: 8)
SchoolUserList.create(school_id: 1, user_id: 8, list_id: 1)
