User.create(first_name: "James", last_name: "Devin", email: "lds1233@gmail.com")
User.create(first_name: "Erin", last_name: "Devin", email: "lds1233@gmail.com")
User.create(first_name: "James", last_name: "Erin", email: "lds1233@gmail.com")
User.create(first_name: "James", last_name: "Bomotti", is_teacher: true, email: "lds1233@gmail.com")
School.create(name: "Novato High School", city: "Novato", state: "CA", district: "Unified")
School.create(name: "San Rafael High School", city: "Novato", state: "CA", district: "Unified")
School.create(name: "Tamalpais High School", city: "Novato", state: "CA", district: "Unified")
School.create(name: "Redwood High School", city: "Novato", state: "CA", district: "Unified")
List.create(quantity: 2, item: "white boards")
List.create(quantity: 20, item: "dry erasers")
List.create(quantity: 10, item: "tissue")
List.create(quantity: 250, item: "iPads")
SchoolUserList.create(school_id: 1, user_id: 4, list_id: 2)
SchoolUserList.create(school_id: 2, user_id: 3, list_id: 2)
SchoolUserList.create(school_id: 4, user_id: 2, list_id: 1)
SchoolUserList.create(school_id: 3, user_id: 4, list_id: 4)
